MODEL:
  TYPE: mobilenetv2_nas
  NUM_CLASSES: 1000
  OP_CODES: [10, 7, 7, 7, 3, 11, 6, 10, 8, 6, 0, 12, 7, 1, 9, 12, 3]
  WIDTH_CODES: [1, 1, 1, 1, 1, 0, 0]
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 1000
    IN_FEAT: 1280
    REDUCTION_DIM: 960
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    MARGIN: 0.15
    SCALE: 30
  LOSSES:
    LABEL_SMOOTHING: 0.1
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.05
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00004
TRAIN:
  DATASET: imagenet
  SPLIT: train_list.txt
  BATCH_SIZE: 160
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val_list.txt
  BATCH_SIZE: 80
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 16
  MIXUP_ALPHA: 0.2
  CUTMIX_ALPHA: 0.2
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_DEST: file
