MODEL:
  TYPE: mobilenetmock
  NUM_CLASSES: 1000
  RANS: [3, 3, 5, 5, 5, 5, 3, 3, 4, 2, 5, 1, 2, 4, 5, 3, 4]
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 1000
    IN_FEAT: 960
    REDUCTION_DIM: 960
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    MARGIN: 0.15
    SCALE: 30
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: imagenet
  SPLIT: train_list.txt
  BATCH_SIZE: 256
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 5
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val_list.txt
  BATCH_SIZE: 800
  IM_SIZE: 224
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 16
  MIXUP_ALPHA: 0.2
  CUTMIX_ALPHA: 0.2
CUDNN:
  BENCHMARK: True
OUT_DIR: .
