MODEL:
  TYPE: mobilenetv2_nas
  DEPTH: 50
  NUM_CLASSES: 1000
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 1000
    IN_FEAT: 1280
    REDUCTION_DIM: 512
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    MARGIN: 0.15
    SCALE: 30
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.025
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 150
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00004
  WARMUP_EPOCHS: 0
TRAIN:
  DATASET: imagenet
  SPLIT: train_list.txt
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val_list.txt
  BATCH_SIZE: 25
  IM_SIZE: 256
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 8
CUDNN:
  BENCHMARK: True
OUT_DIR: .
